services:
  backend:
    build:
      context: .                    
      dockerfile: ./backend/Dockerfile
    container_name: vega-backend
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - vega-network

  frontend:
    build:
      context: .                  
      dockerfile: ./frontend/Dockerfile
    container_name: vega-frontend
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://backend:8000
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - vega-network

networks:
  vega-network:
    driver: bridge